path:
    beamline: /gpfs/bl1/current/processed/timepix_hdf/
    core: /asap3/flash/gpfs/bl1/2019/data/11006902/processed/timepix_hdf/
fragments:
    test_ion:
        tof_start: 1.0575E-5 
        tof_end: 1.0775E-5
        center_x: 134
        center_y: 186
    test_ion2:
        tof_start: 7.65E-6 
        tof_end: 7.99E-6
        center_x: 132
        center_y: 169
    I+:
        tof_start: 7.7E-6 
        tof_end: 8.0E-6
        center_x: 136
        center_y: 172
    I2+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 136
        center_y: 161
    I3+:
        tof_start: 4.90E-6 
        tof_end:  4.95E-6
        center_x: 136
        center_y: 160
    I4+:
        tof_start: 4.37E-6 
        tof_end: 4.40E-6
        center_x: 136
        center_y: 160
    I5+:
        tof_start: 5.2E-6 
        tof_end: 5.4E-6
        center_x: 1
        center_y: 1
    I6+:
        tof_start: 3.74E-6 
        tof_end: 3.79E-6
        center_x: 136
        center_y: 156
    parent+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    parent-I+:
        tof_start: 6.27E-6 
        tof_end: 6.42E-6
        center_x: 134
        center_y: 164
    C+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    N+:
        tof_start: 3.17E-6 
        tof_end: 3.31E-6
        center_x: 134
        center_y: 144
    H+:
        tof_start: 1.5E-6 
        tof_end: 1.61E-6
        center_x: 134
        center_y: 131
fragments_266:
    C5H4N:
        tof_start: 8.2E-6
        tof_end: 8.325E-6
        center_x: 134
        center_y: 172
    I+:
        tof_start: 1.0E-5 
        tof_end: 1.05E-5
        center_x: 134
        center_y: 183
    H+:
        tof_start: 1.7E-6 
        tof_end: 1.9E-6
        center_x: 132
        center_y: 135
    C+:
        tof_start: 3.7E-6 
        tof_end: 3.93E-6
        center_x: 134
        center_y: 144
    H2O+:
        tof_start: 4.45E-6 
        tof_end: 4.5E-6
        center_x: 134
        center_y: 132
    I6+:
        tof_start: 4.7E-6 
        tof_end: 4.8E-6
        center_x: 135
        center_y: 157
    C2Hn+:
        tof_start: 4.9E-6 
        tof_end: 5.4E-6
        center_x: 135
        center_y: 159
    I4+:
        tof_start: 5.585E-6 
        tof_end: 5.635E-6
        center_x: 134
        center_y: 157
    C3Hn+:
        tof_start: 5.8E-6 
        tof_end: 6.25E-6
        center_x: 133
        center_y: 166
    I3+:
        tof_start: 6.26E-6 
        tof_end: 6.41E-6
        center_x: 134
        center_y: 162
    I2+all:
        tof_start: 7.35E-6 
        tof_end: 7.68E-6
        center_x: 134
        center_y: 169
    I2+highE:
        tof_start: 7.47E-6 
        tof_end: 7.6E-6
        center_x: 135
        center_y: 170
