path:
    beamline: /gpfs/bl1/current/processed/timepix_hdf/
    core: /asap3/flash/gpfs/bl1/2019/data/11006902/processed/timepix_hdf/
fragments:
    test_ion:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    test_ion2:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    I+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    I2+:
        tof_start: 7.60E-6 
        tof_end: 8.01E-6
        center_x: 134
        center_y: 118
    I3+:
        tof_start: 6.4E-6 
        tof_end:  6.7E-6
        center_x: 131
        center_y: 127
    I4+:
        tof_start: 5.75E-6 
        tof_end: 5.95E-6
        center_x: 131
        center_y: 127
    I5+:
        tof_start: 5.2E-6 
        tof_end: 5.4E-6
        center_x: 131
        center_y: 127
    I6+:
        tof_start: 4.87E-6 
        tof_end: 4.98E-6
        center_x: 135
        center_y: 96
    parent+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    parent-I+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    C+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    N+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    H+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1