path:
    beamline: /gpfs/bl1/current/processed/timepix_hdf/
    core: /asap3/flash/gpfs/bl1/2019/data/11006902/processed/timepix_hdf/
fragments:
    test_ion:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 134
        center_y: 161
    test_ion2:
        tof_start: 4.33E-6 
        tof_end: 4.50E-6
        center_x: 134
        center_y: 160
    I+:
        tof_start: 7.7E-6 
        tof_end: 8.0E-6
        center_x: 136
        center_y: 172
    I2+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 136
        center_y: 161
    I3+:
        tof_start: 4.90E-6 
        tof_end:  4.95E-6
        center_x: 136
        center_y: 160
    I4+:
        tof_start: 4.37E-6 
        tof_end: 4.40E-6
        center_x: 136
        center_y: 160
    I5+:
        tof_start: 5.2E-6 
        tof_end: 5.4E-6
        center_x: 1
        center_y: 1
    I6+:
        tof_start: 3.74E-6 
        tof_end: 3.79E-6
        center_x: 136
        center_y: 156
    parent+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    parent-I+:
        tof_start: 6.27E-6 
        tof_end: 6.42E-6
        center_x: 134
        center_y: 164
    C+:
        tof_start: 5.6E-6 
        tof_end: 6.0E-6
        center_x: 1
        center_y: 1
    N+:
        tof_start: 3.17E-6 
        tof_end: 3.31E-6
        center_x: 134
        center_y: 144
    H+:
        tof_start: 1.5E-6 
        tof_end: 1.61E-6
        center_x: 134
        center_y: 131